#%RAML 1.0 DataType

properties:
  userName:
    description: This is the Login User Name
    required: true
    type: string
  userPassword:
    description: This is the Login User Password
    required: true
    type: string
