#%RAML 1.0 DataType

properties:
  tenantName:
    description: This is the Tenant Name
    required: true
    type: string
  planName:
    description: This is the Plan Name
    required: true
    type: string
  renewalType:
    description: This is the Renewal Type
    required: true
    type: string
  startDate:
    description: This indicates the Start Date of Subscription
    required: true
    type: string
  endDate:
    description: This indicates the End Date of Subscription
    required: true
    type: string
  isValid:
    description: This indicates whether the Current Subscription is Valid or Not
    required: true
    type: string
